"""empty message

Revision ID: c9ebee2400cd
Revises: 673e26bbe04f
Create Date: 2021-03-30 13:44:29.556007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9ebee2400cd'
down_revision = '673e26bbe04f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('music_videos', sa.Column('coverart', sa.String(), nullable=False))
    op.drop_column('music_videos', 'coverartist')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('music_videos', sa.Column('coverartist', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('music_videos', 'coverart')
    # ### end Alembic commands ###
