"""empty message

Revision ID: 673e26bbe04f
Revises: ffdc0a98111c
Create Date: 2021-03-30 13:39:26.862884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '673e26bbe04f'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('music_videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('coverartist', sa.String(), nullable=False),
    sa.Column('video_url', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lists',
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.Column('music_video_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['music_video_id'], ['music_videos.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['users.id'], )
    )
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('music_video_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['music_video_id'], ['music_videos.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    op.drop_table('lists')
    op.drop_table('music_videos')
    # ### end Alembic commands ###
